name: Copy Repo Code

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  copy-code:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Checkout source repo
        uses: actions/checkout@v2

      - name: Copy code to destination repo
        run: |
          # Set up git config for destination repo
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Create a clone of the destination repo
          git clone -b manyuser https://github.com/NimaQu/shadowsocks.git temp-repo

          # Clear the code in the destination repo
          rm -rf temp-repo/*

          # Copy the code from the source repo to the destination repo
          cp -R $GITHUB_WORKSPACE/* temp-repo/

          # Commit the changes to the destination repo
          cd temp-repo
          git add .
          git commit -m "Copy code from source repo"
          git push origin main

      - name: Clean up
        run: rm -rf temp-repo
